### PR TITLE
Update the Project Roadmap

### PR DESCRIPTION
**Pull request by evanp18**

### CODE REVIEW

**Review by seamansJosh — APPROVED** [review]
Changes Checkout

**Review by docquantum — APPROVED** [review]
this is good

**Review by daniellthibodeau — COMMENTED** [review]
Looks good

**Review by daniellthibodeau — APPROVED** [review]
Looks great

**Review by seamansJosh — APPROVED** [review]

**Review by seamansJosh — APPROVED** [review]
Still looks good @docquantum

**Comment by docquantum** [comment]
@seamansJosh thanks

**Pull request merged**
